### ISSUE TITLE
Vibrate function?

### ISSUE THREAD

**Issue by KeirSweeney** [JISyed/Unity-XboxCtrlrInput#14]
Can't find anything on getting the vibrate to work with these controllers? Am i missing something? It's driving me nuts

**Comment by JISyed** [comment]
Since Unity's standard Input class doesn't support controller vibrations, XboxCtrlrInput doesn't support it, since all the features here should support Windows, Mac, and Linux.

However, if you're on Windows, you should know that XboxCtrlrInput is using [Xinput.Net](https://github.com/speps/XInputDotNet) internally and XInput.Net supports controller vibrations [as seen in the GamePad class](https://github.com/speps/XInputDotNet/blob/406e642aa0b386d2c04a250394a5cf5911d0c131/XInputDotNetPure/GamePad.cs) (scroll all the way to the bottom and find the method `SetVibration()`).

Feel free to modify your fork to include this feature, but since vibrations would only work on Windows, I wouldn't make this official functionality of XboxCtrlrInput unless someone finds out how to make controllers vibrate on Mac and Linux.

**Comment by Jip-Hop** [comment]
Hi,

I've installed the driver from this project: https://github.com/360Controller/360Controller
It supports rumbling. At least it works from the newly added 360Controller Preference Pane.
Perhaps now that OS X can make the controller vibrate, it would be nice to have access to this form Unity too?

**Comment by JISyed** [comment]
In order for vibration to work on macOS, there would have to be a C# library that can access the vibration functionality in the 360Controller driver. There is not any that I know of, so I cannot support vibration (yet). Sorry.

**Comment by JISyed** [comment]
A wiki page was made for this issue: [Concerning Vibration Output](https://github.com/JISyed/Unity-XboxCtrlrInput/wiki/Concerning-Vibration-Output)
