### ISSUE TITLE
[Feature Request] Controller unplugged / re-plugged callbacks.

### ISSUE THREAD

**Issue by PeterVerzijl** [JISyed/Unity-XboxCtrlrInput#17]
Hey JISyed, thanks for making such an awesome plugin. I have a blast using it for my project. I chose for your solutions since it allows for re-connecting to the same 'player' once one or more controllers are disconnected. However, I would like to have a callback function which I could use to change the amount of players for example when someone connects or pause the game if someone disconnects. I would also be able to implement this myself if I had access to the DLL. But sadly no source code is given so I think I won't be able to just yet. Now I have solved the problem by polling for a number change which is extremely ugly. I'd love to hear from you.
Greetings, Peter

**Comment by JISyed** [comment]
Hello Peter,

It may be possible to implement the callback system you described, however, it can only be easily implemented on Windows and not other platforms (Mac & Linux).

The reason for this is because on Windows, XboxCtrlrInput is using a joystick input API that is better than Unity's joystick API (called [XInput.NET](https://github.com/speps/XInputDotNet)), but unfortunately, this API is only available on Windows, so I cannot take advantage of it on Mac or Linux. (The DLLs you mentioned are most likely from XInput.NET, because XboxCtrlrInput itself has no implementation hidden in a DLL, but uses DLLs from XInput.NET for Windows functionality.)

If you want to implement a callback system for controller connections on Windows, feel free to do so, but I cannot pull those features in, because XboxCtrlrInput's aim was to use common Xbox 360 controller functionality that should work on Windows, Mac, and Linux.

To implement a Windows only solution, you would need a [C# event](http://www.akadia.com/services/dotnet_delegates_and_events.html) that can handle the callback of whenever a controller connects or disconnects. This event should probably be called in `XCI.XInputUpdateAllStates()`. But it should only be called if one of the [GamePadStates](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.input.gamepadstate.aspx) are [disconnected](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.input.gamepadstate.isconnected.aspx). The XCI class has an array of 4 GamePadStates, which should be able to tell you if the computer has any controllers that are connected or not. Like I said, this is a Windows feature only.

The callback should probably use a [C# delegate](http://www.codeproject.com/Articles/11657/Understanding-Delegates-in-C) that has parameters like the controller number, and whether the controller was connected or disconnected.

Unfortunately, there is really no easy way to get a similar callback system to work using only Unity APIs on Mac and Linux. There is [`Input.GetJoystickNames()`](http://docs.unity3d.com/ScriptReference/Input.GetJoystickNames.html), but it's very unreliable, especially if you have more than one of the same controllers plugged in to the computer. I also heard about another method where you could check the raw input of one axis to see if the controller is still alive, but I found this to be unreliable as well (I tested it), so there is no good solution on Mac and Linux to check controller connections.

I'm sorry I wasn't able to help too much with this. Best of luck with your project.

**Comment by TonyTonijn** [comment]
Hey JISyed,

I was able to implement the functionality I wanted in the end. As you described I called the C# event and used delegates to watch the XCI.XInputUpdateAllStates() getting called. I also found out the XInput.NET's repo and got some very interesting information there. However, due to the way XInput works, there is no interrupt I could handle. So basically I am still polling. Which is sort of bad. But anyway, thanks a lot for setting me on the right path! I hope that Microsoft writes decent software for the xbox360 controllers that works multi-platform in a nice way.

What I did stumble upon is that the Standard Input Module only supports one x and one y axis. I might implement one which does the same thing but takes an array of x and y axis for input in the Unity GUI. If I finish that I might add it to your project so people can use your awesome solution for the GUI system as well. For now I just implement my own Selectable functions for all the menus.

And don't be sorry, your help was humongous! Greetings and thanks. My project is coming together quite nicely!
