### ISSUE TITLE
Unity 5.0 on OSX doesn't show controller connected

### ISSUE THREAD

**Issue by joshuajnoble** [JISyed/Unity-XboxCtrlrInput#18]
I'm running Unity 5.0 and OSX 10.11.3. After installing the newest release of [360Controller](https://github.com/360Controller/360Controller/releases) I can see the controller working fine in the Preferences Pane but not in Unity. Adding the following near the initialization of the controller gives me back a '0' result. Any thoughts on what might be causing the issue?

````
		print (" Num plugged controllers " + XCI.GetNumPluggedCtrlrs ());
```

**Comment by joshuajnoble** [comment]
This was solved by installing an older version of 360Controller, [the 0.15 Beta 3 release](https://github.com/360Controller/360Controller/releases/tag/v0.15_beta3_unofficial). Not sure if it's just my setup or ctrlrInput

**Comment by JISyed** [comment]
I'll be honest, I don't know what was causing your issue because you're using beta drivers. I myself had an old driver installed, and the controller stopped working until I installed the latest stable driver release. Sorry I couldn't be of help.

For anyone else reading this, make sure you use the latest drivers from [360Contoller](https://github.com/360Controller/360Controller/releases) that joshuanoble mentioned above, but use the latest stable release (version 0.14 at the time of this writting), unless you're feeling adventerous.

**Comment by joshuajnoble** [comment]
Yeah, should have closed this myself. As always beta drivers are risky, but 0.15b3 works.
