### ISSUE TITLE
Support for Vibration (Rumble)?

### ISSUE THREAD

**Issue by gkgkgkgk** [JISyed/Unity-XboxCtrlrInput#23]
I did not see it in the Docs but maybe I am missing it. If not, will there be support for vibration/rumble in the future? Huge fan of this repo, by the way..... it is a lifesaver. Unity's built in input system is not intuitive. Or can I implement vibration in a different way? Thanks.

**Comment by pedro15** [comment]
`using XInputDotNetPure;
 using UnityEngine;
void Start ()
{
        GamePad.SetVibration(PlayerIndex.One, 5f, 5f);
}
`

I think it only would work on windows ...

**Comment by gkgkgkgk** [comment]
Thanks! Ill try it ASAP. Luckily I'm on Windows.....
The args for the SetVibration method are controller, left, right?

**Comment by pedro15** [comment]
The args are :  PlayerIndex , Left motor force  , Right motor force .

**Comment by gkgkgkgk** [comment]
Excellent! Thanks so much.



via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.3.88&pv=6.0.1&source=email_footer_2] On Fri, Mar 03, 2017 at 9:33am, Pedro Duran < notifications@github.com [notifications@github.com] > wrote:
The args are : PlayerIndex , Left motor force , Right motor force .

**Comment by JISyed** [comment]
I cannot add controller vibration functionality into XCI because it would only work on Windows. On Windows, XCI uses XInput.NET, which is a Windows-only C# library. On Mac and Linux, controller input is polled from Unity's Input API, which has no vibration support. My intention was to make functionality in XCI multiplatform.

I will keep this issue open since there have been similar requests for vibration functionality (see issue #14).

**Comment by JISyed** [comment]
A wiki page was made for this issue: [Concerning Vibration Output](https://github.com/JISyed/Unity-XboxCtrlrInput/wiki/Concerning-Vibration-Output).

As such, I'll close the issue
