### ISSUE TITLE
Problem with deadzones

### ISSUE THREAD

**Issue by josencv** [JISyed/Unity-XboxCtrlrInput#25]
Hi,

I was having problem with deazones because they are being calculated in an axial way (as explained [here](http://www.third-helix.com/2013/04/12/doing-thumbstick-dead-zones-right.html)).

The code:

```cs
// Note: the variable "rawAxisValue" represents the value of a single axis
// Clear axis value if less than the deadzone
if(Mathf.Abs(rawAxisValue) < deadzone)
{
    finalValue = 0.0f;
}
// Remap the axis value from interval [0,1] to [deadzone,1]
else
{
    finalValue = (Mathf.Abs(rawAxisValue) * (1 - deadzone)) + deadzone;
    finalValue = finalValue * Mathf.Sign(rawAxisValue);
}
```

This was producing a sticky effect in the cardinal directions.

I investigated the code further and discovered that for Windows platforms the deadzone was already being applied in the XInputDotNetPure lib (with radial deadzone), so I set all the deadzones to 0 in the InputManager and now everything works OK, but I don't know what'll happen in other platforms.

Maybe the library should add radial deadzones as well, and probably a flag to let XInputDotNetPure handle the deadzones, for Windows at least (it uses constant deadzones values btw).

**Comment by JISyed** [comment]
I tried to wrangle with deadzone code in order to fix another bug that someone else reported long ago, but he found out an alternative solution. Long story short, my deadzone code became obsolete, so I removed it altogether, and the player movement is now much better on Windows (not to mention the code is simpler now).

I released [a new version of XCI](https://github.com/JISyed/Unity-XboxCtrlrInput/releases/tag/1.7.0) that addresses this problem. If it works, feel free to close this issue.
